name: mobility_mate
description: "Helping persons of all abilities to navigate the world with ease and confidence."
publish_to: 'none' # Prevents accidental pub.dev publishing
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Official Mapbox Maps SDK for Flutter (iOS & Android)
  mapbox_maps_flutter: ^2.7.0  #  [oai_citation_attribution:0‡Dart packages](https://pub.dev/packages/mapbox_maps_flutter)

  # HTTP client
  http: ^1.1.0

  # Local persistence
  shared_preferences: ^2.2.2

  # iOS-style icons
  cupertino_icons: ^1.0.8
  
  url_launcher: ^6.1.14
  share_plus: ^11.0.0
  geolocator: ^10.1.0
  image_picker: ^1.0.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints for better code quality
  flutter_lints: ^5.0.0

  # For generating launcher icons (downgraded to avoid conflicts)
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png
    - assets/suburb_stations.json
    - assets/icon/toilet.png

